spring.application.name=glucose-control-service

spring.datasource.url=jdbc:postgresql://localhost:5432/glucose_control_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver