spring.application.name=glucose-control-service

springdoc.api-docs.path=api/v1/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.with-credentials=true
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.csrf.cookie-name=XSRF-TOKEN
springdoc.swagger-ui.csrf.header-name=X-XSRF-TOKEN
springdoc.swagger-ui.config-url=/api/v1/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v1/api-docs

spring.datasource.url=jdbc:postgresql://localhost:5432/glucose_control_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.data.web.pageable.max-page-size=20

cors.frontend.url=http://localhost:5173

spring.profiles.active=local