CREATE TYPE glucose_unit AS ENUM ('MILLIMOLES_PER_LITER', 'MILLIGRAMS_PER_DECILITER');
CREATE TYPE carbs_unit AS ENUM ('GRAMS', 'BREAD_UNITS_10', 'BREAD_UNITS_12', 'BREAD_UNITS_15');
CREATE TYPE insulin_type AS ENUM ('SHORT', 'LONG');
CREATE TYPE measurement_type AS ENUM ('BEFORE_MEAL', 'AFTER_MEAL');

CREATE TABLE Service_User (
    id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username varchar(255) UNIQUE NOT NULL,
    password varchar NOT NULL
);

CREATE TABLE User_Role (
                           user_id int REFERENCES service_user(id) ON DELETE CASCADE,
                           role varchar,
                           PRIMARY KEY (user_id, role)
);

CREATE TABLE Role_Authority (
    role varchar,
    authority varchar,
    is_deletable bool DEFAULT false,
    PRIMARY KEY (role, authority)
);

CREATE TABLE Patient_Profile (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int UNIQUE REFERENCES service_user(id) ON DELETE CASCADE,
    glucose_unit glucose_unit NOT NULL DEFAULT 'MILLIMOLES_PER_LITER',
    carbs_unit carbs_unit NOT NULL DEFAULT 'GRAMS',
    diabetes_type smallint CHECK (diabetes_type IN (1, 2))
);

-- CREATE TABLE Diary_Entry (
--     profile_id int REFERENCES Patient_Profile(id) ON DELETE CASCADE,
--     commited_at timestamptz(0) NOT NULL,
--     notes varchar(500),
--     type entry_type,
--     PRIMARY KEY (profile_id, commited_at)
-- );

CREATE TABLE Glucose_Entry (
    profile_id int REFERENCES Patient_Profile(id) ON DELETE CASCADE,
    value real NOT NULL CHECK (value >= 0.5 AND value <= 40),
    commited_at timestamptz(0) NOT NULL,
    measurement_type measurement_type,
    notes varchar(500),
    PRIMARY KEY (profile_id, commited_at)
);

CREATE TABLE Insulin_Entry (
    profile_id int REFERENCES Patient_Profile(id) ON DELETE CASCADE,
    value real NOT NULL CHECK (value >= 1 AND value <= 100),
    commited_at timestamptz(0) NOT NULL,
    insulin_type insulin_type NOT NULL,
    notes varchar(500),
    PRIMARY KEY (profile_id, commited_at)
);

CREATE TABLE Medication_Entry (
    profile_id int REFERENCES Patient_Profile(id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    value real NOT NULL CHECK (value >= 0 AND value <= 1000),
    commited_at timestamptz(0) NOT NULL,
    notes varchar(500),
    PRIMARY KEY (profile_id, commited_at)
);

CREATE TABLE Meal_Entry (
    profile_id int REFERENCES Patient_Profile(id) ON DELETE CASCADE,
    value real NOT NULL CHECK (value >= 0 AND value <= 300),
    commited_at timestamptz(0) NOT NULL,
    notes varchar(500),
    PRIMARY KEY (profile_id, commited_at)
);
